bookShare/urls.py
from django.urls import path 
from bookShare import views

app_name = 'bookShare'
urlpatterns = [
    path('', views.browse, name='browse'),
    path('browse/', views.browse, name='browse'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('<str:user_id>/profile/', views.profile, name='profile'),
    path('book/<str:book_id>/', views.book_info, name='book_info'),
    path('book/<str:book_id>/edit/', views.edit_book, name='edit_book'),
    path('book/<str:book_id>/add_interest/',views.add_interest, name="add_interest"),
    path('book/<str:book_id>/remove_interest/', views.remove_interest, name="remove_interest"),
    path('book/<str:book_id>/accept_interest/<str:reserved_user_id>/',views.accept_interest, name="accept_interest"),
    path('new_listing/', views.add_book, name='add_book'),
    path('search/', views.user_search, name = 'user_search'),
    path('<str:user_id>/profile/edit', views.edit_profile, name="edit_profile"),
    path('<str:user_id>/follow/', views.follow, name="follow"),
    path('<str:user_id>/unfollow/', views.unfollow, name="unfollow"),
    path('<str:user_id>/profile/followers', views.show_followers, name ="followers"),
    path('<str:user_id>/profile/following', views.show_following, name ="following"),
    path('webhook/',views.webhook, name="web_hook"),
]

book_share/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from bookShare import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.browse, name='index'),
    path('bookShare/', include('bookShare.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookShare/views/accept_interest.py
from bookShare.models import Interest, UserProfile, Book, User
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required(login_url="bookShare:login")
def accept_interest(request, book_id, reserved_user_id):
    book = Book.objects.get(book_id=book_id)
    if UserProfile.objects.filter(user=request.user).exists() and book.user_profile == UserProfile.objects.get(user = request.user):
        if book.is_reserved == False:
            book.is_reserved = True;
            book.reserved_user = UserProfile.objects.get(user=User.objects.get(username=reserved_user_id))
        else:
            book.is_reserved = False;
            book.reserved_user = None;
        book.save()


    return redirect(reverse('bookShare:book_info', kwargs={'book_id':book_id}))

bookShare/views/add_book.py
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from bookShare.forms import BookForm
from bookShare.models import Book, UserProfile
from django.urls import reverse

@login_required(login_url="bookShare:login")
def add_book(request):
    added = False
    submitted = False
    context = {}
    if request.method == 'POST':
        

        book_form = BookForm(request.POST)
        if book_form.is_valid():
            user = request.user
            user_profile = UserProfile.objects.get(user = user)
            user_profile.reputation += 1;
            user_profile.save()
            book = book_form.save(commit=False)
            book.user_profile = user_profile
            if "cover_image" in request.FILES:
                book.cover_image = request.FILES['cover_image']
            book.upload_time = datetime.datetime.now
            book.is_reserved = False
            book.save()
            return redirect(reverse("bookShare:book_info", kwargs={'book_id':book.book_id}))            
        else:
            context["errors"] = book_form.errors
        
        submitted =True
        
    else:
        book_form = BookForm()

    context['book_form'] = book_form
    context["added"] = added
    context["submitted"] = submitted

    
    return render(request,'bookShare/add_book.html', context=context)

bookShare/views/add_interest.py
from bookShare.models import Interest, UserProfile, Book
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

@login_required(login_url="bookShare:login")
def add_interest(request,book_id):
    book = Book.objects.get(book_id=book_id)
    if request.is_ajax and request.method == 'POST' and request.user.username != book.user_profile.user.username and UserProfile.objects.filter(user = request.user).exists():
        user_profile = UserProfile.objects.get(user = request.user)
        if not Interest.objects.filter(book_id=book_id,user_profile=user_profile).exists():
            Interest.objects.create(book_id=book_id,user_profile=user_profile)

        return JsonResponse({}, status=200)
    
    return redirect(reverse('bookShare:book_info', kwargs={'book_id':book_id}))

bookShare/views/add_intrest.py
from bookShare.models import Interest, UserProfile, Book
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required(login_url="bookShare:login")
def add_interest(request,book_id):
    book = Book.objects.get(book_id=book_id)
    if request.user.username != book.user_profile.user.username and UserProfile.objects.filter(user = request.user).exists():
        user_profile = UserProfile.objects.get(user = request.user)
        if not Interest.objects.filter(book_id=book_id,user_profile=user_profile).exists():
            Interest.objects.create(book_id=book_id,user_profile=user_profile)
    
    return redirect(reverse('bookShare:book_info', kwargs={'book_id':book_id}))

bookShare/views/book_info.py
from django.shortcuts import render
from bookShare.models import Book, UserProfile, Interest
from django.shortcuts import redirect
from django.urls import reverse
from bookShare.views.map_functions import getCoordsContextDict


def book_info(request, book_id):
    try:
        context = getCoordsContextDict(book_id)
    except:
        context = {"invalid_map": True}
    try:
        book = Book.objects.get(book_id=book_id)
    except:
        return redirect(reverse("bookShare:browse"))
    context['book'] = book
    if book.is_reserved:
        context["interested_users"] = Interest.objects.filter(book_id=book_id).filter(
            user_profile__user__username=book.reserved_user.user.username)
    else:
        context["interested_users"] = Interest.objects.filter(book_id=book_id)
    if request.user.is_authenticated and UserProfile.objects.filter(user=request.user).exists():
        user_profile = UserProfile.objects.get(user=request.user)
        context['interested'] = Interest.objects.filter(
            book_id=book_id, user_profile=user_profile).exists()
        context['user_books'] = Book.objects.filter(
            user_profile__user__username=book.user_profile.user.username).count()
    else:
        context['interested'] = 'invalid'

    return render(request, 'bookShare/book_info.html', context=context)

bookShare/views/browse.py
from django.db.models import Q, Count
from django.http import JsonResponse
from django.shortcuts import render
import json

from bookShare.models import Book, UserProfile, Follows

from .map_functions import getCoordsRequest
from bookShare.utils.map_calculations import getLatLon


def browse(request):
    context = {}
    if request.method == "POST":
        general_query = request.POST["general_query"]
        checkbox_querys = json.loads(request.POST["checkbox_queries"]) if "checkbox_queries" in request.POST else {}
        try:
            max_radius = int(request.POST["max_radius_query"])
        except ValueError:
            max_radius = 100_000_000  # Effectively infinity if no or incorrect input
        postcode = request.POST["postcode"]
        lat, lon = getLatLon(postcode)
        valid_postcode = lat != None
        available_only = True if request.POST["available_only"] == "true" else False
        following_only = True if request.POST["following_only"] == "true" else False
        mine_only = True if request.POST["mine_only"] == "true" else False
        reserved_for_me_only = True if request.POST["reserved_for_me_only"] == "true" else False
        sort_order = request.POST["sort"]

        # Select all books which contain the general query in any field
        results = Book.objects.filter(Q(title__icontains=general_query) | Q(author__icontains=general_query) | Q(isbn__icontains=general_query) | Q(
            genre__icontains=general_query) | Q(book_id__icontains=general_query) | Q(user_profile__user__username__icontains=general_query))
        
        # Filter books
        if "authors" in checkbox_querys:
            results = results.filter(author__in=checkbox_querys["authors"])
        if "publishers" in checkbox_querys:
            results = results.filter(
                publisher__in=checkbox_querys["publishers"])
        if "genres" in checkbox_querys:
            results = results.filter(genre__in=checkbox_querys["genres"])

        if available_only:
            results = results.filter(is_reserved__exact=False)

        if following_only:
            results = results.filter(user_profile__in=Follows.objects.filter(
                follower=UserProfile.objects.get(user=request.user)
            ).values_list("following"))

        if mine_only:
            results = results.filter(user_profile__user=request.user)

        if reserved_for_me_only:
            results = results.filter(reserved_user__user=request.user)
        
        if valid_postcode:
            try:
                ids = [book.book_id for book in results if book.user_profile.getDistance(
                    lat, lon) <= max_radius]
                results = results.filter(book_id__in=ids)
            except:
                pass

        # Sort results into correct order
        context["results"] = sort_results(results, sort_order, lat, lon)
        
        return JsonResponse({"results_container": render(request, 'bookShare/browse_results.html', context=context).content.decode("utf-8"), "valid_postcode": valid_postcode})

    else:
        context["dropdowns"] = {
            "genres": Book.objects.values_list("genre").annotate(total=Count("genre")),
            "authors": Book.objects.values_list("author").annotate(total=Count("author")),
            "publishers": Book.objects.values_list("publisher").annotate(total=Count("publisher")),
        }
        print(context)
        if request.user.is_authenticated and UserProfile.objects.filter(user=request.user).exists():
            context["user_postcode"] = UserProfile.objects.get(
                user=request.user).post_code
        return render(request, 'bookShare/browse.html', context=context)


def sort_results(query_set, sort_order, user_lat, user_lon):
    orderings = {
        "az": "title",
        "za": "-title",
        "newest_first": "-upload_time",
        "oldest_first": "upload_time",
        "lowest_reputation_first": "user_profile__reputation",
        "highest_reputation_first": "-user_profile__reputation",
    }
    if orderings.get(sort_order):
        return query_set.order_by(orderings.get(sort_order))
    # Only sort by distance if a valid location is given
    elif (sort_order == "closest_first" or sort_order == "furthest_first") and user_lat != None:
        books = [book for book in query_set]
        books.sort(key=lambda book: book.user_profile.getDistance(
            user_lat, user_lon))
        if sort_order == "furthest_first":
            books.reverse()
        return books
    else:
        # Invalid sort input, so order alphabetically
        return query_set.order_by("title")

bookShare/views/edit_book.py
from bookShare.forms import BookForm
from django.contrib.auth.models import User
from bookShare.models import Book
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


@login_required(login_url='bookShare:login')
def edit_book(request, book_id):
    book = Book.objects.get(book_id=book_id)
    book_user_id = book.user_profile.user.username
    if request.user.username != book_user_id:
        # ensures only the user that listed the book can edit it.
        return redirect(reverse('bookShare:browse'))

    print(request.method)
    if request.method == 'POST':
        profile_form = BookForm(request.POST, instance=book)

        if profile_form.is_valid():

            if 'cover_image' in request.FILES:
                book.cover_image.delete(save=True)
                book.cover_image = request.FILES['cover_image']
            else:
                profile_form.cover_image = book.cover_image

            profile_form.save()

            return redirect(reverse('bookShare:book_info', kwargs={'book_id': book_id}))
        else:
            print(profile_form.errors)

    else:
        profile_form = BookForm(
            {
                'title': book.title,
                'publisher': book.publisher,
                'author': book.author,
                'isbn': book.isbn,
                'genre': book.genre
            }
        )

    return render(request, 'bookShare/edit_book.html',
                  context={
                      'bookForm': profile_form,
                      'book': book,
                      'book_id': book_id,
                      'book_user_id': book_user_id
                  })

bookShare/views/edit_profile.py
from bookShare.forms import UserProfileForm
from django.contrib.auth.models import User
from bookShare.models import UserProfile
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required(login_url='bookShare:login')
def edit_profile(request, user_id):
    if request.user.username != user_id:
        return redirect(reverse('bookShare:browse')) # Not valid user

    profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':

        profile_form = UserProfileForm(request.POST, instance=profile)

        if profile_form.is_valid():
            

            if 'user_image' in request.FILES:
                profile.user_image.delete(save=True)
                profile.user_image = request.FILES['user_image']
            else:
                profile_form.user_image = profile.user_image

            profile_form.save()

            return redirect(reverse('bookShare:profile', kwargs={'user_id':user_id}))
        else:
            print(profile_form.errors)
    else:
        profile_form = UserProfileForm(instance=profile)

    
    return render(request,
        'bookShare/edit_profile.html',
        context = {
        'profile_form': profile_form,
        'user_id':user_id,
        'location':profile.location,
        'post_code':profile.post_code,
        'phone_number':profile.phone_number,
        })

bookShare/views/follow.py
from django.shortcuts import render
from django.contrib.auth.models import User
from bookShare.models import Follows, UserProfile
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

@login_required
def follow(request, user_id):
    if request.is_ajax and request.method == "POST" and request.user.username != user_id:
        other_user = UserProfile.objects.get(user=User.objects.get(username=user_id))
        profile = UserProfile.objects.get(user=request.user)

        if not Follows.objects.filter(follower=profile, following=other_user).exists():
            Follows.objects.create(follower=profile, following=other_user)
        
        return JsonResponse({"follow_count":len(Follows.objects.filter(following=other_user))}, status=200)

    return redirect(reverse('bookShare:profile', kwargs={'user_id':user_id}))

bookShare/views/intrest.py
from bookShare.models import Interest, UserProfile, Book
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

bookShare/views/login.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect

def user_login(request):
    if request.user.is_authenticated:
        return redirect(reverse('bookShare:browse')) # Already signed in.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('bookShare:browse'))
            else:
                return render(request, 'bookShare/login.html', context={"error_msg":"Your BookShare account is disabled."})
        else:
            print(f"Invalid login details: {username}, {password}")
            return render(request, 'bookShare/login.html', context={"error_msg":"Invalid login details supplied"})
    else:
        return render(request, 'bookShare/login.html')

bookShare/views/logout.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('bookShare:browse'))

templates/bookShare/add_book.html
{% extends 'bookShare/base.html' %}

{% load staticfiles %}

{% block title %}Add Book{% endblock %}
{% block content %}
    {% include "bookShare/components/card_start.html" with card_title="Add Book" %}

    <form id="book_form"
          method="post"
          action="{% url 'bookShare:add_book' %}"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="flex flex-col gap-4 mb-6">
            {% include "bookShare/components/input.html" with type="text" name="title" label="Title" required=True placeholder="Harry Potter" %}
            {% include "bookShare/components/input.html" with type="text" name="publisher" label="Publisher" required=True placeholder="Bloomsbury" %}
            {% include "bookShare/components/input.html" with type="text" name="author" label="Author" required=True placeholder="JK,Rowling" %}
            {% include "bookShare/components/input.html" with type="text" name="isbn" label="ISBN" required=True placeholder="9780747532743" maxlength=13 %}
            {% include "bookShare/components/input.html" with type="File" name="cover_image" label="Cover Image" required=False placeholder="" %}
            {% include "bookShare/components/input.html" with type="text" name="genre" label="Genre" required=True placeholder="Fantasy" %}

        </div>
        <input role="button" class="btn-primary mb-6" type="submit" name="submit" />
    </form>
    {% if submitted %}
        {% if added %}
            <h3>Book added!</h3>
        {% elif errors %}
        <h3> Book not added! Errors: </h3>
        <ul>
            {% for error in errors %}
                <li> Invalid {{error|upper}} </li>
            {%endfor%}
        </ul>
        {% endif %}
    {% endif %}
    {% include "bookShare/components/card_end.html" %}

{% endblock %}

templates/bookShare/book_info.html
{% extends 'bookShare/base.html' %}

{% load staticfiles %}

{% block title %}Book Info{% endblock %}
{% block javascript %}
    <script>
    var bookId = '{{book.book_id}}';
    var isInterested = {{interested|lower}};
    </script>
    <script src = {% static 'js/ajax-register-interest.js' %}></script>
{% endblock %}
{% block content %}
    <div class="flex gap-10 md:gap-20 flex-col md:flex-row my-0 md:my-20">
        <div class="md:w-[40%] md:shadow-md md:rounded-xl md:p-11 flex justify-center items-center relative">
            {% if book.cover_image %}
                <img class="md:absolute top-0 h-[100%] py-5"
                     src="{{ book.cover_image.url }}"/>
            {% else %}
                <img src="{% static 'images/default_book.jpg' %}" />
            {% endif %}
        </div>
        <div class="text-black flex-1">
            <h1 class="text-4xl md:text-5xl font-semibold text-black mb-6 w-[80%] md:w-[70%]">{{ book.title }}</h1>
            <p class="underline underline-offset-2">{{ book.author }}</p>
            <div class="relative overflow-x-auto my-6 w-full md:w-[70%]">
                <table class="table">
                    <thead class="thead">
                        <tr>
                            <th scope="col">Attribute</th>
                            <th scope="col">Value</th>
                        </tr>
                    </thead>
                    <tbody class="tbody">
                        <tr>
                            <th scope="row">Publisher</th>
                            <td>{{ book.publisher }}</td>
                        </tr>
                        <tr>
                            <th scope="row">ISBN</th>
                            <td>{{ book.isbn }}</td>
                        </tr>
                        <tr class="bg-white dark:bg-gray-800">
                            <th scope="row">Genre</th>
                            <td>{{ book.genre }}</td>
                        </tr>
                        <tr class="bg-white dark:bg-gray-800">
                            <th scope="row">Added since</th>
                            <td>{{ book.upload_time }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-lg flex gap-5 items-center pt-2">
                {% if user.username == book.user_profile.user.username %}
                    <a href="{% url 'bookShare:edit_book' book.book_id %}"
                       class="btn-primary">Edit</a>
                {% elif user.is_authenticated and interested != "invalid" %}
                    <button {% if book.is_reserved %}disabled{% endif %}
                            class="btn-primary"
                            id="change-interest-button">
                        {% if book.is_reserved and user.username == book.reserved_user.user.username %}
                            Reserved for you!
                        {% elif book.is_reserved %}
                            Reserved for {{ book.reserved_user.user.username }}
                        {% elif interested %}
                            Remove Interest
                        {% else %}
                            Register Interest
                        {% endif %}
                    </button>
                    <a href="mailto:{{ book.user_profile.user.email }}">Contact</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="mt-10 sm:mt-0">
        {% if user.is_authenticated and book.reserved_user and user.username == book.reserved_user.user.username %}
            <p class="font-semibold">Reserved for you!</p>
            The poster of this listing should be in contact with you soon.
            <br>
            You can contact them through their email: <a class="underline underline-offset-4 text-blue"
    href="mailto:{{ book.user_profile.user.email }}">{{ book.user_profile.user.email }}</a>
        {% endif %}
        {% if user.username == book.user_profile.user.username %}
            <h2 class="text-2xl font-semibold pb-5">
                {% if book.is_reserved %}
                    Reserved for
                {% else %}
                    Interested Users
                {% endif %}
            </h2>
            <table class="table">
                <thead class="thead">
                    <tr>
                        <th>User</th>
                        <th>Email</th>
                        <th class="hidden sm:table-cell">Phone Number</th>
                        <th class="hidden sm:table-cell">Reserve?</th>
                    </tr>
                </thead>
                <tbody class="tbody">
                    {% for user in interested_users %}
                        <tr>
                            <td>
                                <a href="{% url 'bookShare:profile' user.user_profile.user.username %}"
                                   class="flex items-center space-x-4">
                                    <img class="w-10 h-10 rounded-full object-cover"
                                         src="{% if user.user_profile.user_image %} {{ user.user_profile.user_image.url }} {% else %} {% static 'images/default_pfp.jpg' %} {% endif %}"
                                         alt="Profile">
                                    <div class="font-medium dark:text-white">
                                        <div class="text-black">{{ user.user_profile.user.username }}</div>
                                        <div class="text-sm text-gray-500">Joined in {{ book.user_profile.user.date_joined|date:"F Y" }}</div>
                                    </div>
                                </a>
                            </td>
                            <td class="hidden sm:table-cell">{{ user.user_profile.user.email }}</td>
                            <td class="hidden sm:table-cell">
                                {% if user.user_profile.phone_number %}
                                    {{ user.user_profile.phone_number }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'bookShare:accept_interest' book.book_id user.user_profile.user.username %}"
                                   class="btn-primary"
                                   {% if book.is_reserved and book.reserved_user.user.username != user.user_profile.user.username %}disabled="true"{% endif %}>
                                    {% if book.is_reserved and book.reserved_user.user.username == user.user_profile.user.username %}
                                        Unreserve
                                    {% else %}
                                        Reserve
                                    {% endif %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
    {% if user.username != book.user_profile.user.username %}
        <div class="mapSection shadow-sm flex gap-0 mt-10 md:mt-20 flex-col md:flex-row">
            <div class="mapSidebar md:rounded-l-lg p-11 pr-20 bg-blue text-white">
                <p class="text-slate-100 text-[15px]">added by:</p>
                <div class="text-3xl my-3 font-semibold">{{ book.user_profile.user.username }}</div>
                <ul class="text-[18px] text-white pl-3 flex flex-col gap-3">
                    <li class="flex gap-3 items-center">
                        <span class="w-2 h-2 bg-white rounded-full"></span>
                        Joined since {{ book.user_profile.user.date_joined|date:"F Y" }}
                    </li>
                    <li class="flex gap-3 items-center">
                        <span class="w-2 h-2 bg-white rounded-full"></span>
                        Reputation Score: {{ book.user_profile.reputation }}
                    </li>
                    <li class="flex gap-3 items-center">
                        <span class="w-2 h-2 bg-white rounded-full"></span>
                        Books: {{ user_books }}
                    </li>
                </ul>
                <div class="mt-10">
                    <a href="{% url 'bookShare:profile' book.user_profile.user.username %}"
                       class="btn-primary white">View Profile</a>
                </div>
            </div>
            <div class="bg-gray block md:flex-1 relative h-[360px]">
                <p class="absolute top-[50%] left-[50%] translate-y-[-50%] translate-x-[-50%] text-3xl text-gray-500">
                    Map is loading...
                </p>
                {% include "bookShare/components/map.html" %}

            </div>
        </div>
    {% endif %}
{% endblock %}

templates/bookShare/profile.html
{% extends 'bookShare/base.html' %}

{% load staticfiles %}

{% block title %}{{ profile.user.username }}{% endblock %}
{% block javascript %}
    <script>
    var isFollowing = {{is_following|lower}}
    var username = '{{profile.user.username}}'
    </script>
    <script src = {% static 'js/ajax-follow.js' %}></script>
{% endblock %}
{% block content %}
    {% include "bookShare/components/card_start.html" with card_title=profile.user.username %}

    <div class="flex gap-5 sm:gap-10">
        <img class="object-cover rounded-lg w-[50%]"
             src="{% if profile.user_image %}{{ profile.user_image.url }}{% else %}{% static 'images/default_pfp.jpg' %}{% endif %}"/>
        <div>
            {% for key,attribute in profile_attributes.items %}
                <div>
                    <span class="text-xs">{{ attribute.label }}</span>
                    <p class="text-md sm:text-lg font-semibold">{{ attribute.value }}</p>
                </div>
            {% endfor %}
            {% if user.username == profile.user.username %}
                <a class="btn-primary inline-block mt-4"
                   href="{% url 'bookShare:edit_profile' user.username %}">Edit</a>
            {% elif user.is_authenticated and is_following != "invalid" %}
                <button class="btn-primary inline-block mt-4" id="change-follow-button">
                    {% if is_following %}
                        Unfollow
                    {% else %}
                        Follow
                    {% endif %}
                </button>
            {% endif %}
        </div>
    </div>
    <div class="text-center sm:text-right flow-root flex flex-col gap-4 mb-6">
        <div class="text-center block float-left w-full mb-3" id = "lower-content">
            <hr class = "mt-7 mb-3">
            <div class="sm:ml-20 ml-4 block float-left" id = "following">
                <span class = "text-xs block">Following</span>
                <span class="text-3xl"><b><a id="following-count"
   href="{% url 'bookShare:following' profile.user.username %}">{{ following|length }}</a> </b></span>
            </div>
            <div class = "block float-right mr-4 sm:mr-20" id = "followers">
                <span class = "text-xs block">Followers</span>
                <span class="text-3xl"><b><a id="follower-count"
   href="{% url 'bookShare:followers' profile.user.username %}">{{ followers|length }}</a> </b></span>
            </div>
        </div>
        <hr class = "w-full mb-7">
        <div class="w-full h-full">
            {% include "bookShare/components/map.html" %}

        </div>
    </div>
    {% include "bookShare/components/card_end.html" %}

{% endblock %}