bookShare/urls.py
from django.urls import path 
from bookShare import views

app_name = 'bookShare'
urlpatterns = [
    path('', views.browse, name='browse'),
    path('browse/', views.browse, name='browse'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('<str:user_id>/profile/', views.profile, name='profile'),
    path('book/<str:book_id>/', views.book_info, name='book_info'),
    path('book/<str:book_id>/edit/', views.edit_book, name='edit_book'),
    path('book/<str:book_id>/add_interest/',views.add_interest, name="add_interest"),
    path('book/<str:book_id>/remove_interest/', views.remove_interest, name="remove_interest"),
    path('book/<str:book_id>/accept_interest/<str:reserved_user_id>/',views.accept_interest, name="accept_interest"),
    path('new_listing/', views.add_book, name='add_book'),
    path('search/', views.user_search, name = 'user_search'),
    path('<str:user_id>/profile/edit', views.edit_profile, name="edit_profile"),
    path('<str:user_id>/follow/', views.follow, name="follow"),
    path('<str:user_id>/unfollow/', views.unfollow, name="unfollow"),
    path('<str:user_id>/profile/followers', views.show_followers, name ="followers"),
    path('<str:user_id>/profile/following', views.show_following, name ="following"),
    path('webhook/',views.webhook, name="web_hook"),
]

book_share/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from bookShare import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.browse, name='index'),
    path('bookShare/', include('bookShare.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookShare/views/accept_interest.py
from bookShare.models import Interest, UserProfile, Book, User
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required(login_url="bookShare:login")
def accept_interest(request, book_id, reserved_user_id):
    book = Book.objects.get(book_id=book_id)
    if UserProfile.objects.filter(user=request.user).exists() and book.user_profile == UserProfile.objects.get(user = request.user):
        if book.is_reserved == False:
            book.is_reserved = True;
            book.reserved_user = UserProfile.objects.get(user=User.objects.get(username=reserved_user_id))
        else:
            book.is_reserved = False;
            book.reserved_user = None;
        book.save()


    return redirect(reverse('bookShare:book_info', kwargs={'book_id':book_id}))

bookShare/views/add_book.py
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from bookShare.forms import BookForm
from bookShare.models import Book, UserProfile
from django.urls import reverse

@login_required(login_url="bookShare:login")
def add_book(request):
    added = False
    submitted = False
    context = {}
    if request.method == 'POST':
        

        book_form = BookForm(request.POST)
        if book_form.is_valid():
            user = request.user
            user_profile = UserProfile.objects.get(user = user)
            user_profile.reputation += 1;
            user_profile.save()
            book = book_form.save(commit=False)
            book.user_profile = user_profile
            if "cover_image" in request.FILES:
                book.cover_image = request.FILES['cover_image']
            book.upload_time = datetime.datetime.now
            book.is_reserved = False
            book.save()
            return redirect(reverse("bookShare:book_info", kwargs={'book_id':book.book_id}))            
        else:
            context["errors"] = book_form.errors
        
        submitted =True
        
    else:
        book_form = BookForm()

    context['book_form'] = book_form
    context["added"] = added
    context["submitted"] = submitted

    
    return render(request,'bookShare/add_book.html', context=context)

bookShare/views/add_interest.py
from bookShare.models import Interest, UserProfile, Book
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

@login_required(login_url="bookShare:login")
def add_interest(request,book_id):
    book = Book.objects.get(book_id=book_id)
    if request.is_ajax and request.method == 'POST' and request.user.username != book.user_profile.user.username and UserProfile.objects.filter(user = request.user).exists():
        user_profile = UserProfile.objects.get(user = request.user)
        if not Interest.objects.filter(book_id=book_id,user_profile=user_profile).exists():
            Interest.objects.create(book_id=book_id,user_profile=user_profile)

        return JsonResponse({}, status=200)
    
    return redirect(reverse('bookShare:book_info', kwargs={'book_id':book_id}))

bookShare/views/add_intrest.py
from bookShare.models import Interest, UserProfile, Book
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required(login_url="bookShare:login")
def add_interest(request,book_id):
    book = Book.objects.get(book_id=book_id)
    if request.user.username != book.user_profile.user.username and UserProfile.objects.filter(user = request.user).exists():
        user_profile = UserProfile.objects.get(user = request.user)
        if not Interest.objects.filter(book_id=book_id,user_profile=user_profile).exists():
            Interest.objects.create(book_id=book_id,user_profile=user_profile)
    
    return redirect(reverse('bookShare:book_info', kwargs={'book_id':book_id}))

bookShare/views/book_info.py
from django.shortcuts import render
from bookShare.models import Book, UserProfile, Interest
from django.shortcuts import redirect
from django.urls import reverse
from bookShare.views.map_functions import getCoordsContextDict


def book_info(request, book_id):
    try:
        context = getCoordsContextDict(book_id)
    except:
        context = {"invalid_map": True}
    try:
        book = Book.objects.get(book_id=book_id)
    except:
        return redirect(reverse("bookShare:browse"))
    context['book'] = book
    if book.is_reserved:
        context["interested_users"] = Interest.objects.filter(book_id=book_id).filter(
            user_profile__user__username=book.reserved_user.user.username)
    else:
        context["interested_users"] = Interest.objects.filter(book_id=book_id)
    if request.user.is_authenticated and UserProfile.objects.filter(user=request.user).exists():
        user_profile = UserProfile.objects.get(user=request.user)
        context['interested'] = Interest.objects.filter(
            book_id=book_id, user_profile=user_profile).exists()
        context['user_books'] = Book.objects.filter(
            user_profile__user__username=book.user_profile.user.username).count()
    else:
        context['interested'] = 'invalid'

    return render(request, 'bookShare/book_info.html', context=context)

bookShare/views/browse.py
from django.db.models import Q, Count
from django.http import JsonResponse
from django.shortcuts import render
import json

from bookShare.models import Book, UserProfile, Follows

from .map_functions import getCoordsRequest
from bookShare.utils.map_calculations import getLatLon


def browse(request):
    context = {}
    if request.method == "POST":
        general_query = request.POST["general_query"]
        checkbox_querys = json.loads(request.POST["checkbox_queries"]) if "checkbox_queries" in request.POST else {}
        try:
            max_radius = int(request.POST["max_radius_query"])
        except ValueError:
            max_radius = 100_000_000  # Effectively infinity if no or incorrect input
        postcode = request.POST["postcode"]
        lat, lon = getLatLon(postcode)
        valid_postcode = lat != None
        available_only = True if request.POST["available_only"] == "true" else False
        following_only = True if request.POST["following_only"] == "true" else False
        mine_only = True if request.POST["mine_only"] == "true" else False
        reserved_for_me_only = True if request.POST["reserved_for_me_only"] == "true" else False
        sort_order = request.POST["sort"]

        # Select all books which contain the general query in any field
        results = Book.objects.filter(Q(title__icontains=general_query) | Q(author__icontains=general_query) | Q(isbn__icontains=general_query) | Q(
            genre__icontains=general_query) | Q(book_id__icontains=general_query) | Q(user_profile__user__username__icontains=general_query))
        
        # Filter books
        if "authors" in checkbox_querys:
            results = results.filter(author__in=checkbox_querys["authors"])
        if "publishers" in checkbox_querys:
            results = results.filter(
                publisher__in=checkbox_querys["publishers"])
        if "genres" in checkbox_querys:
            results = results.filter(genre__in=checkbox_querys["genres"])

        if available_only:
            results = results.filter(is_reserved__exact=False)

        if following_only:
            results = results.filter(user_profile__in=Follows.objects.filter(
                follower=UserProfile.objects.get(user=request.user)
            ).values_list("following"))

        if mine_only:
            results = results.filter(user_profile__user=request.user)

        if reserved_for_me_only:
            results = results.filter(reserved_user__user=request.user)
        
        if valid_postcode:
            try:
                ids = [book.book_id for book in results if book.user_profile.getDistance(
                    lat, lon) <= max_radius]
                results = results.filter(book_id__in=ids)
            except:
                pass

        # Sort results into correct order
        context["results"] = sort_results(results, sort_order, lat, lon)
        
        return JsonResponse({"results_container": render(request, 'bookShare/browse_results.html', context=context).content.decode("utf-8"), "valid_postcode": valid_postcode})

    else:
        context["dropdowns"] = {
            "genres": Book.objects.values_list("genre").annotate(total=Count("genre")),
            "authors": Book.objects.values_list("author").annotate(total=Count("author")),
            "publishers": Book.objects.values_list("publisher").annotate(total=Count("publisher")),
        }
        print(context)
        if request.user.is_authenticated and UserProfile.objects.filter(user=request.user).exists():
            context["user_postcode"] = UserProfile.objects.get(
                user=request.user).post_code
        return render(request, 'bookShare/browse.html', context=context)


def sort_results(query_set, sort_order, user_lat, user_lon):
    orderings = {
        "az": "title",
        "za": "-title",
        "newest_first": "-upload_time",
        "oldest_first": "upload_time",
        "lowest_reputation_first": "user_profile__reputation",
        "highest_reputation_first": "-user_profile__reputation",
    }
    if orderings.get(sort_order):
        return query_set.order_by(orderings.get(sort_order))
    # Only sort by distance if a valid location is given
    elif (sort_order == "closest_first" or sort_order == "furthest_first") and user_lat != None:
        books = [book for book in query_set]
        books.sort(key=lambda book: book.user_profile.getDistance(
            user_lat, user_lon))
        if sort_order == "furthest_first":
            books.reverse()
        return books
    else:
        # Invalid sort input, so order alphabetically
        return query_set.order_by("title")

bookShare/views/edit_book.py
from bookShare.forms import BookForm
from django.contrib.auth.models import User
from bookShare.models import Book
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


@login_required(login_url='bookShare:login')
def edit_book(request, book_id):
    book = Book.objects.get(book_id=book_id)
    book_user_id = book.user_profile.user.username
    if request.user.username != book_user_id:
        # ensures only the user that listed the book can edit it.
        return redirect(reverse('bookShare:browse'))

    print(request.method)
    if request.method == 'POST':
        profile_form = BookForm(request.POST, instance=book)

        if profile_form.is_valid():

            if 'cover_image' in request.FILES:
                book.cover_image.delete(save=True)
                book.cover_image = request.FILES['cover_image']
            else:
                profile_form.cover_image = book.cover_image

            profile_form.save()

            return redirect(reverse('bookShare:book_info', kwargs={'book_id': book_id}))
        else:
            print(profile_form.errors)

    else:
        profile_form = BookForm(
            {
                'title': book.title,
                'publisher': book.publisher,
                'author': book.author,
                'isbn': book.isbn,
                'genre': book.genre
            }
        )

    return render(request, 'bookShare/edit_book.html',
                  context={
                      'bookForm': profile_form,
                      'book': book,
                      'book_id': book_id,
                      'book_user_id': book_user_id
                  })

bookShare/views/edit_profile.py
from bookShare.forms import UserProfileForm
from django.contrib.auth.models import User
from bookShare.models import UserProfile
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required(login_url='bookShare:login')
def edit_profile(request, user_id):
    if request.user.username != user_id:
        return redirect(reverse('bookShare:browse')) # Not valid user

    profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':

        profile_form = UserProfileForm(request.POST, instance=profile)

        if profile_form.is_valid():
            

            if 'user_image' in request.FILES:
                profile.user_image.delete(save=True)
                profile.user_image = request.FILES['user_image']
            else:
                profile_form.user_image = profile.user_image

            profile_form.save()

            return redirect(reverse('bookShare:profile', kwargs={'user_id':user_id}))
        else:
            print(profile_form.errors)
    else:
        profile_form = UserProfileForm(instance=profile)

    
    return render(request,
        'bookShare/edit_profile.html',
        context = {
        'profile_form': profile_form,
        'user_id':user_id,
        'location':profile.location,
        'post_code':profile.post_code,
        'phone_number':profile.phone_number,
        })

bookShare/views/follow.py
from django.shortcuts import render
from django.contrib.auth.models import User
from bookShare.models import Follows, UserProfile
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

@login_required
def follow(request, user_id):
    if request.is_ajax and request.method == "POST" and request.user.username != user_id:
        other_user = UserProfile.objects.get(user=User.objects.get(username=user_id))
        profile = UserProfile.objects.get(user=request.user)

        if not Follows.objects.filter(follower=profile, following=other_user).exists():
            Follows.objects.create(follower=profile, following=other_user)
        
        return JsonResponse({"follow_count":len(Follows.objects.filter(following=other_user))}, status=200)

    return redirect(reverse('bookShare:profile', kwargs={'user_id':user_id}))

bookShare/views/intrest.py
from bookShare.models import Interest, UserProfile, Book
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

bookShare/views/login.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect

def user_login(request):
    if request.user.is_authenticated:
        return redirect(reverse('bookShare:browse')) # Already signed in.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('bookShare:browse'))
            else:
                return render(request, 'bookShare/login.html', context={"error_msg":"Your BookShare account is disabled."})
        else:
            print(f"Invalid login details: {username}, {password}")
            return render(request, 'bookShare/login.html', context={"error_msg":"Invalid login details supplied"})
    else:
        return render(request, 'bookShare/login.html')

bookShare/views/logout.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('bookShare:browse'))

templates/bookShare/components/button.html
{% if ctxt %}
<a class="btn-primary" href="{% url url ctxt %}">{{ label }}</a>
{% else %}
<a class="btn-primary" href="{% url url %}">{{ label }}</a>
{% endif %}

templates/bookShare/components/card_end.html
</div>
</div>

templates/bookShare/components/card_start.html
<div class="flex justify-center items-center w-full">
  <div class="max-w-[650px] lg:w-[500px] shadow-lg rounded-xl p-7 sm:p-11 my-5">
    <h1 class="text-5xl font-semibold text-black mb-11 text-center">{{ card_title }}</h1>

templates/bookShare/components/footer.html
<footer class=" bg-gray text-black">
  <div class="container">
    <div class="flex gap-5 py-10 flex-col sm:flex-row sm:w-9/12">
      <div class="sm:w-2/5">
        <h3 class="text-3xl font-semibold mb-5 sm:leading-[80px]">BookShare</h3>
        <p class="max-w-[90%]">
          Discover a world of books with Bookshare. Whether you're looking for the latest bestsellers or timeless classics our app makes it easy to find your next favorite book. Join today and discover new books for free.
        </p>
      </div>
      <div class="sm:w-1/5">
        <h3 class="text-3xl font-semibold mb-5 sm:leading-[80px]">Menu</h3>
        <ul class="flex flex-col gap-3">
          <li>
            <a href="{% url 'bookShare:browse' %}">Browse</a>
          </li>
          <li>
            <a href="{% url 'bookShare:login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'bookShare:register' %}">Register</a>
          </li>
        </ul>
      </div>
      <div>
        <h3 class="text-3xl font-semibold mb-5 sm:leading-[80px]">Recently Added</h3>
        <ul class="flex flex-col gap-3">
          {% for book in latest_added_books %}
            <li>
              <a href="{% url 'bookShare:book_info' book.book_id %}">{{ book.title }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="copyright">
      <p>© {% now "Y" %} - BookShare</p>
    </div>
  </div>
</footer>

templates/bookShare/components/header.html
{% load static %}

<header class="container py-[15px]">
  <div class="flex flex-col gap-4 sm:gap-0 sm:flex-row sm:justify-between content-center">
    <div class="flex justify-between">
      <a class="block" href="{% url 'bookShare:browse' %}">
        <img class="h-[90px]"
             src="{% static 'images/logo-transparent.png' %}"
             alt="Logo">
      </a>
      <button id="btn-hamburger"
              class="inline-flex sm:hidden items-center justify-center p-2 rounded-md text-black focus:outline-none">
        <span class="sr-only">Open main menu</span>
        <svg class="icon-menu-closed block h-10 w-10"
             xmlns="http://www.w3.org/2000/svg"
             viewBox="0 0 24 24"
             stroke-width="2"
             stroke-linecap="round"
             stroke-linejoin="round">
          <path stroke="currentColor" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
        <svg class="icon-menu-open hidden h-10 w-10"
             xmlns="http://www.w3.org/2000/svg"
             viewBox="0 0 24 24"
             stroke-width="2"
             stroke-linecap="round"
             stroke-linejoin="round">
          <path stroke="currentColor" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>
    <nav class="flex bg-gray rounded-md sm:bg-transparent sm:p-0 items-center overflow-hidden box-border max-h-0 sm:max-h-none">
      <ul class="p-[15px] sm:p-0 flex flex-col sm:flex-row sm:items-center gap-4 sm:gap-10 text-lg sm:text-xl text-black">
        {% for item in left_nav_items %}
          <li>
            <a href="{% url item.url %}">{{ item.name }}</a>
          </li>
        {% endfor %}
        <li class="sm:border-l-[1px] border-gray">
          <div class="sm:pl-10 flex items-center gap-5">
            {% if user.is_authenticated %}
              <a href="{% url 'bookShare:logout' %}">Logout</a>
            {% else %}
              <a href="{% url 'bookShare:login' %}">Login</a>
            {% endif %}
            {% if user.is_authenticated %}
              {% include "bookShare/components/button.html" with label="Profile" url="bookShare:profile" ctxt=user.username %}

            {% else %}
              {% include "bookShare/components/button.html" with label="Sign up" url="bookShare:register" %}

            {% endif %}
          </div>
        </li>
      </ul>
    </nav>
  </div>
  <script>
    const button = document.querySelector('#btn-hamburger');
    const menuClosedIcon = button.querySelector('.icon-menu-closed');
    const menuOpenIcon = document.querySelector('.icon-menu-open');
    const nav = document.querySelector('nav');
    button.addEventListener('click', () => {
      menuClosedIcon.classList.toggle('hidden');
      menuOpenIcon.classList.toggle('hidden');
      nav.classList.toggle('max-h-0');
    });
  </script>
</header>

templates/bookShare/components/input.html
<label class="block">
  <span class="block text-sm font-medium text-slate-700 {% if required %}after:content-['*'] after:ml-0.5 after:text-red-500{% endif %}">{{ label }}</span>
  <input type={{ type }} {%if type == "File"%} accept="image/*"{%endif%}  name={{ name }} maxlength={{maxlength|default:128}} class="input" placeholder={{ placeholder|default:'' }} />
</label>

templates/bookShare/components/map.html
{% load static %}

{% if invalid_map == True %}
  <div id="map">Invalid Postcode - Can't display map.</div>
{% else %}
  <p hidden id="latitude">{{ latitude }}</p>
  <p hidden id="longitude">{{ longitude }}</p>
  <p hidden id="centreLat">{{ centreLat }}</p>
  <p hidden id="centreLon">{{ centreLng }}</p>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  <script type="module" src="{% static 'js/mapDisplay.js'%}"></script>
  <div id="map"></div>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyZOguzi85PD4EvAj9f-3CL_TXthYzbyQ&callback=initMap&v=weekly"
          defer></script>
  <script src="{% static 'js/mapBonus.js' %}"></script>
{% endif %}

templates/bookShare/components/search_bar.html
<div class="w-[500px]">
  <form id = "{{ form_id }}" enctype = "multipart/form-data">
    {% comment %} <input type = "submit" name = "submit" value = "Search"> {% endcomment %}
    <label for="general_query_field"
           class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">
      {{ label }}
    </label>
    <div class="relative">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg aria-hidden="true"
             class="w-5 h-5 text-gray-500 "
             fill="none"
             stroke="currentColor"
             viewBox="0 0 24 24"
             xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z">
          </path>
        </svg>
      </div>
      <input type="search"
             id="{{ input_id }}"
             name="general_query"
             class="block w-full p-4 pl-10 text-md text-gray-900 border border-gray rounded-lg bg-gray-50 focus:ring-blue-400 focus:border-blue-400 "
             placeholder="{{ placeholder }}">
      {% if show_button %}
        <button type="submit"
                class="text-white absolute right-2.5 bottom-2.5 bg-blue hover:bg-blue-900 focus:ring-4 focus:outline-none focus:ring-blue font-medium rounded-lg text-md px-4 py-2 ">
          {{ label }}
        </button>
      {% endif %}
    </div>
  </form>
</div>

templates/bookShare/components/user_grid_item.html
{% load staticfiles %}

<div class="shadow-md rounded-lg ">
    <a class="w-full block relative h-[250px] bg-gray-50 rounded-t-lg"
       href="{% url 'bookShare:profile' username %}">
        <img class="absolute top-0 left-0 w-full h-full object-contain z-0" src={% if image_url != "none" %}{{ image_url }}{% else %}"{% static 'images/default_pfp.jpg' %}"{% endif %} />
    </a>
    <div class="px-5 py-4 relative">
        <a class="block font-semibold text-xl mb-1"
           href="{% url 'bookShare:profile' username %}">{{ username }}</a>
        <p class="text-gray-600">{{ location }}</p>
    </div>
</div>